# Please modify the settings below according to your needs.

# List of source URLs to fetch proxy configurations from.
# Add or remove URLs as needed. All URLs in this list are automatically enabled.
# توصیه می‌شود از URLهای معتبر و عمومی استفاده کنید تا از مسدود شدن IP خود جلوگیری شود.
SOURCE_URLS = [
    "https://raw.githubusercontent.com/4n0nymou3/wg-config-fetcher/refs/heads/main/configs/wireguard_configs.txt",
    "https://raw.githubusercontent.com/4n0nymou3/ss-config-updater/refs/heads/main/configs.txt",
 "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_1.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_2.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_3.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_4.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_1.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_2.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_3.txt",
    "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_4.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista4.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista5.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista6.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista7.txt",
    "https://raw.githubusercontent.com/Aristaproject/AristaSub/refs/heads/main/Arista8.txt",

    "https://t.me/s/shadowsocksm",
    "https://t.me/s/v2ray_alpha",
    "https://t.me/s/vlessconfig",
    "https://t.me/s/v2rayngvpn",
    "https://t.me/s/an0nymousteam",
    "https://t.me/s/oneclickvpnkeys",
    "https://t.me/s/cav2ray",
    "https://t.me/s/eliv2ray",
    "https://t.me/s/mehradlearn",
    "https://t.me/s/outline_vpn",
    "https://t.me/s/safenet_server",
    "https://t.me/s/vpn_king_v2ray",
    "https://t.me/s/ipv2ray",
    "https://t.me/s/lrnbymaa",
    "https://t.me/s/proxy_kafee",
    "https://t.me/s/proxy_mtm",
    "https://t.me/s/v2rayng_vpnn",
    "https://t.me/s/tv2rayrr",
    "https://t.me/s/v2rey_hiddify",
    "https://t.me/s/server_nekobox",
    "https://t.me/s/v2rayngn",
    "https://t.me/s/v2raying",
    "https://t.me/s/s0013_official",
    "https://t.me/s/v2rayroz",
    "https://t.me/s/v2rayng_outlinee",
    "https://t.me/s/sinavm",
    "https://t.me/s/customv2ray",
    "https://t.me/s/fastkanfig",
    "https://t.me/s/vpnstorefast",
    "https://t.me/s/hope_net",
    "https://t.me/s/oxnet_ir",
    "https://t.me/s/cryptoguardvpn",
    "https://t.me/s/freeiranianv2rey",
    "https://t.me/s/ernoxin_shop",
    "https://t.me/s/darkvpnpro",
    "https://t.me/s/free_vpn_for_all_of_us",
    "https://t.me/s/noforcedheaven",
    "https://t.me/s/v2raybaz",
    "https://t.me/s/freedomofinfor",
    "https://t.me/s/vpnstable",
    "https://t.me/s/orange_vpns",
    "https://t.me/s/amirtronic",
    "https://t.me/s/kb_v2ray_store",
    "https://t.me/s/freevpnhomesconfigs",
    "https://t.me/s/ahmedhamoomi_servers",
    "https://t.me/s/v2ray_nima02",
    "https://t.me/s/isvvpn",
    "https://t.me/s/prossh",
    "https://t.me/s/v2ray_hub1",
    "https://t.me/s/grizzlyvpn",
    "https://t.me/s/bestforbest66",
    "https://t.me/s/curetech",
    "https://t.me/s/v2source",
    "https://t.me/s/getconfigir",
    "https://t.me/s/parsashonam",
    "https://t.me/s/arv2ray",
    "https://t.me/s/configfa",
    "https://t.me/s/change_ip1",
    "https://t.me/s/vpncustomize",
    "https://t.me/s/suevpnx",
    "https://t.me/s/nfastvpnn",
    "https://t.me/s/napsternetv",
    "https://t.me/s/alpha_v2ray_iran",
    "https://t.me/s/vpn_proxy666",
    "https://t.me/s/xsfilternet",
    "https://t.me/s/hiidify_v2ray",
    "https://t.me/s/configwireguard",
    "https://t.me/s/wirevpnguard",
    "https://t.me/s/lonup_m",
    "https://t.me/s/configv2rayng",
    "https://t.me/s/v2ray_tunnel_plus",
    "https://t.me/s/cookvip",
    "https://t.me/s/v2rayfree",
    "https://t.me/s/freev2rays",
    "https://t.me/s/v2ray_free_conf",
    "https://t.me/s/privatevpns",
    "https://t.me/s/ip_cf_config",
    "https://t.me/s/shadowproxy66",
    "https://t.me/s/outlinereleasedkey",
    "https://t.me/s/prrofile_purple",
    "https://t.me/s/proxy_shadosocks",
    "https://t.me/s/meli_proxyy",
    "https://t.me/s/directvpn",
    "https://t.me/s/vmessprotocol",
    "https://t.me/s/viproxys",
    "https://t.me/s/heyatserver",
    "https://t.me/s/vpnfail_vless",
    "https://t.me/s/dailyv2ry",
    "https://t.me/s/qv2rayconfig",
    "https://t.me/s/xsfilternetv2",
    "https://t.me/s/redfree8",
    "https://t.me/s/azadnet",
    "https://t.me/s/v2sayfree",
    "https://t.me/s/safenet4all",
    "https://t.me/s/golestan_vpn",
    "https://t.me/s/mehduox_vpn",
    "https://t.me/s/kayh_gng",
    "https://t.me/s/xrovpn",
    "https://t.me/s/viturey",
    "https://t.me/s/freedom_guard_net",
    "https://t.me/s/ln2ray",
    "https://t.me/s/zeusvpn_net",
    "https://t.me/s/v2nodes",
    "https://t.me/s/v2box_free",
    "https://t.me/s/vpnaloo",
    "https://t.me/s/v2ray_hidify",
    "https://t.me/s/purnet",
    "https://t.me/s/soskeynet",
    "https://t.me/s/begzarvpn",
    "https://t.me/s/proxydaemi",
    "https://t.me/s/slamvpn",
    "https://t.me/s/vpnz4",
    "https://t.me/s/hack_androidapp1",
    "https://t.me/s/p_tech2024",
    "https://t.me/s/yebekhe",
    "https://t.me/s/fr33c0nfig",
    "https://t.me/s/aristaproject",
    "https://t.me/s/kevinzakarian",
    "https://t.me/s/marambashi",
    "https://t.me/s/vpn_solve",
    "https://t.me/s/vpn4everyone",
    "https://t.me/s/ahwazigamingshop",
    "https://t.me/s/prooofsor",
    "https://t.me/s/mrsoulb",
    "https://t.me/s/surfboardv2ray",
    "https://t.me/s/v2ray_vpn_ir",
    "https://t.me/s/vpnbaz",
    "https://t.me/s/asrnovin_ir",
    "https://t.me/s/capoit",
    "https://t.me/s/conectvpn10",
    "https://t.me/s/spotify_porteghali",
    "https://t.me/s/ar14n24b",
    "https://t.me/s/xixv2ray",
    "https://t.me/s/movie10_oficial",
    "https://t.me/s/beau_vpn",
    "https://t.me/s/mitivpn",
    "https://t.me/s/mbtiuniverse",
    "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/juicity",
    "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/tuic",
    "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/reality",
     "https://raw.githubusercontent.com/huibq/trojanlinks/refs/heads/master/links/ssr",
    "https://raw.githubusercontent.com/hiddify/hiddify-next/refs/heads/main/test.configs/warp",
    "https://raw.githubusercontent.com/ircfspace/warpsub/refs/heads/main/export/warp",
    "https://raw.githubusercontent.com/maimengmeng/mysub/refs/heads/main/valid_content_all.txt",
    "https://rayan-config.github.io/ng",
    "https://raw.githubusercontent.com/rayan-config/c-sub/refs/heads/main/configs/proxy.txt",
    "https://raw.githubusercontent.com/rayan-config/c-sub/refs/heads/main/configs/singbox_configs.json",
    "https://t.me/s/rayan_config",
    "https://t.me/s/configshubplus",
    "https://t.me/s/configx2ray",
    "https://t.me/s/speeds_vpn1",
    "https://t.me/s/betv2ray",
    "https://t.me/s/bugfreenet",
    "https://t.me/s/canfing_vpn",
    "https://t.me/s/crypto_trad26",
    "https://t.me/s/express_freevpn",
    "https://t.me/s/gp_config",
    "https://t.me/s/proxy_confiig",
    "https://t.me/s/proxyiranip",
    "https://t.me/s/club_profsor",
    "https://t.me/s/vless_config",
    "https://t.me/s/vlessconfight",
    "https://t.me/s/freeconfigsplus",
    "https://t.me/s/madshopx",
    "https://t.me/s/vpnserverrr"
]

# True را برای واکشی حداکثر تعداد ممکن کانفیگ‌ها تنظیم کنید.
# اگر True باشد، SPECIFIC_CONFIG_COUNT نادیده گرفته می‌شود.
USE_MAXIMUM_POWER = False

# تعداد مورد نظر کانفیگ برای واکشی.
# این فقط در صورتی استفاده می‌شود که USE_MAXIMUM_POWER برابر False باشد.
SPECIFIC_CONFIG_COUNT = 400

# دیکشنری پروتکل‌ها برای فعال یا غیرفعال کردن.
# هر پروتکل را روی True تنظیم کنید تا فعال شود، False برای غیرفعال کردن.
# توجه: پروتکل‌های جدید (SSR، Mieru، Snell، Anytls، SSH، Juicity، Hysteria، WARP) به Singbox تبدیل نمی‌شوند.
ENABLED_PROTOCOLS = {
    "wireguard://": True,
    "hysteria2://": True, # شامل hy2:// هم می‌شود
    "vless://": True,
    "vmess://": True,
    "ss://": True,
    "trojan://": True,
    "tuic://": True,
    "ssr://": True,       # ShadowsocksR
    "mieru://": True,     # Mieru
    "snell://": True,     # Snell
    "anytls://": True,    # Anytls
    "ssh://": True,       # SSH
    "juicity://": True,   # Juicity
    "hysteria://": True,  # Hysteria 1 (شامل hy1:// هم می‌شود)
    "warp://": True       # Cloudflare WARP
}

# حداکثر عمر کانفیگ‌ها بر حسب روز.
# کانفیگ‌های قدیمی‌تر از این مقدار نامعتبر تلقی می‌شوند.
MAX_CONFIG_AGE_DAYS = 2
